const names = [
    "New York City",
    "Paris",
    "Tokyo",
    "London",
    "Sydney",
    "Rome",
    "Los Angeles",
    "Dubai",
    "Berlin",
    "Moscow",
    "Toronto",
    "Singapore",
    "Barcelona",
    "Rio de Janeiro",
    "Amsterdam",
    "Seoul",
    "Venice",
    "Cairo",
    "Bangkok",
    "Mexico City",
    "Istanbul",
    "San Francisco",
    "Madrid",
    "Mumbai",
    "Vienna",
    "Prague",
    "Hong Kong",
    "Buenos Aires",
    "Athens",
    "Florence",
    "Stockholm",
    "Kyoto",
    "Cape Town",
    "Chicago",
    "Shanghai",
    "Lisbon",
    "Montreal",
    "Dublin",
    "Budapest",
    "Osaka",
    "Helsinki",
    "Warsaw",
    "Melbourne",
    "San Diego",
    "Edinburgh",
    "Zurich",
    "Vancouver",
    "Brussels",
    "Munich"
];

var container="";
names.forEach(function(name){
   container +=`   <h3 class="text-lg tracking-tight px-3 py-2">${name}</h3>`;
});
document.querySelector(".scrollercustom").innerHTML=container;